logging:
  level:
    root: info
    
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:123
      username: root
      password: 1